#! /bin/bash

#General Directory Declarations
START_DIR=$PWD
INSTALL_DIR=/etc/kalivnc
BACKUP_DIR=/etc/kalivnc/backups
SCRIPTS_DIR=/usr/bin
KALIVNC_DIR=/etc/kalivnc/rpi-kalivnc-installer
VNC_SERVER_DIR=/home/kali/.vnc
UNINSTALL=/usr/bin/rpi-kalivnc-uninstaller
UNINSTALL_BAK=/etc/kalivnc/rpi-kalivnc-installer/rpi-kalivnc-uninstaller
INITD=/etc/init.d/vncserver
INITD_BAK=/etc/kalivnc/rpi-kalivnc-installer/vncserver
XSTARTUP=/home/kali/.vnc/xstartup
XSTARTUP_BAK=/etc/kalivnc/rpi-kalivnc-installer/xstartup
XSTARTUP_BAK_DIR=/etc/kalivnc/backups/xstartup.bak

#URL Declarations
INSTALLER_GIT_URL=https://github.com/xXNightstalkerXx/rpi-kalivnc-installer.git
INSTALLER_WGET_URL=https://raw.github.com/xXNightstalkerXx/rpi-kalivnc-installer/master/rpi-kalivnc-installer

#Color Declarations
std=$(tput setaf 15)
red=$(tput setaf 9 bold)
green=$(tput setaf 10 bold)
yellow=$(tput setaf 11 bold)
pink=$(tput setaf 57)
blue=$(tput setaf 27 bold)

#Main Script
echo ""
echo ""
echo "${blue}//      //   ///     //   //////////${std}"
echo "${blue}//     //   ////    //   //${std}"
echo "${blue}//    //   // //   //   //${std}"
echo "${blue}//   //   //  //  //   //${std}"
echo "${blue}//  //   //   // //   //${std}"
echo "${blue}// //   //    ////   //${std}"
echo "${blue}////   //     ///   ///////////${std}"
echo "Kali X11 VNC Uninstaller by Nightstalker"
echo ""
echo ""
echo "${blue}Checking OS...${std}"
os_type="$(grep -E '^(NAME)=' /etc/os-release)"
os_type=${os_type#*=}

if [[ "$os_type" == *"Kali"* ]]
then
	echo ""
	echo "$os_type"
else
	echo ""
	echo "${red}Wrong Operating System detected! Aborting to Uninstall!${std}"
	sleep 1
	exit 1
fi

echo ""
echo "${blue}Operating System okay! Continuing to Uninstall!${std}"
sleep 1

echo ""
echo ""
echo "${blue}Uninstalling the VNC Server...${std}"
echo ""
echo "${blue}Purging X11 VNC from the System...${std}"
sudo apt-get purge x11vnc -y
echo "${blue}Deleting leftover User Directory $VNC_SERVER_DIR ...${std}"
sudo rm -d -r $VNC_SERVER_DIR
echo "${blue}Deleting $INITD ...${std}"
sudo rm $INITD
echo ""
echo "${blue}VNC Server successfully uninstalled! Continuing to Uninstall!${std}"
sleep 1

echo ""
echo ""
echo "${blue}Checking Directories...${std}"
echo ""
echo "${blue}Checking Installation Directory...${std}"
echo "$INSTALL_DIR"
if [ -d "$INSTALL_DIR" ]
then
    echo "${blue}Installation Directory exists. Deleting this Directory!${std}"
    sudo rm -d -r $INSTALL_DIR
else
    echo "${red}Installation Directory doesn't exist. Not able to delete!${std}"
fi
echo ""
echo "${blue}Directories sucessfully deleted! Continuing to Uninstall!${std}"
sleep 1

echo ""
echo ""
echo "${blue}Deleting Script Files in ${SCRIPTS_DIR} Directory...${std}"
echo ""
echo "${blue}Switching into Directory...${std}"
echo "$SCRIPTS_DIR"
cd $SCRIPTS_DIR
echo ""
echo "${blue}Purging myself now!${std}"
sleep 1

echo ""
echo ""
echo "${blue}Uninstall completed, Good bye!${std}"
echo ""
sudo rm $UNINSTALL
